const cron = require("node-cron")
const mongoose = require("mongoose")
const nodemailer = require("nodemailer")
const Order = require("../models/Order")
const User = require("../models/User")

const sendMonthlyReport = async () => {
    // Check if database is connected before running
    if (mongoose.connection.readyState !== 1) {
        return console.warn("[MONTHLY-REPORT] Skipping job: Database not connected")
    }

    try {
        const now = new Date()
        // Calculate first and last day of the previous month
        const firstDayPrevMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1)
        const lastDayPrevMonth = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59, 999)

        const monthName = firstDayPrevMonth.toLocaleString('default', { month: 'long' })
        const year = firstDayPrevMonth.getFullYear()

        console.log(`[MONTHLY-REPORT] Generating report for ${monthName} ${year}...`)

        // 1. Calculate Monthly Revenue using Aggregation
        const revenueData = await Order.aggregate([
            {
                $match: {
                    status: "completed",
                    createdAt: {
                        $gte: firstDayPrevMonth,
                        $lte: lastDayPrevMonth
                    }
                }
            },
            {
                $group: {
                    _id: null,
                    totalRevenue: { $sum: "$totalAmount" },
                    totalOrders: { $count: {} }
                }
            }
        ])

        const stats = revenueData.length > 0 ? revenueData[0] : { totalRevenue: 0, totalOrders: 0 }

        // 2. Fetch Admin Email Recipients
        // The user requirement mentions an "emails" array. 
        // We fetch admins and collect all available email addresses.
        const admins = await User.find({ role: "admin" })

        // Support both the existing 'email' string and the requested 'emails' array
        const recipientEmails = admins.reduce((acc, admin) => {
            if (admin.email) acc.push(admin.email)
            if (Array.isArray(admin.emails)) acc.push(...admin.emails)
            return acc
        }, [])

        const uniqueRecipients = [...new Set(recipientEmails)]

        if (uniqueRecipients.length === 0) {
            return console.warn("[MONTHLY-REPORT] No admin emails found. Report not sent.")
        }

        // 3. Configure Nodemailer
        const transporter = nodemailer.createTransport({
            service: process.env.EMAIL_SERVICE || 'gmail',
            auth: {
                user: process.env.EMAIL_USER,
                pass: process.env.EMAIL_PASS
            }
        })

        const restaurantName = process.env.RESTAURANT_NAME || "OG Restaurant"

        // 4. Send Email
        const emailContent = `
<h2>${restaurantName} Monthly Revenue Report</h2>
<p><strong>Month:</strong> ${monthName} ${year}</p>
<hr />
<p><strong>Total Monthly Revenue:</strong> ₹${stats.totalRevenue.toLocaleString('en-IN')}</p>
<p><strong>Total Orders:</strong> ${stats.totalOrders}</p>
<hr />
<p>This is an automated report generated by your Restaurant Management System.</p>
    `

        const mailOptions = {
            from: `"${restaurantName}" <${process.env.EMAIL_USER}>`,
            to: uniqueRecipients.join(", "),
            subject: `${restaurantName} Monthly Revenue Report - ${monthName} ${year}`,
            html: emailContent
        }

        const info = await transporter.sendMail(mailOptions)
        console.log(`[MONTHLY-REPORT] Email sent successfully: ${info.messageId} to ${uniqueRecipients.length} recipients`)

    } catch (error) {
        console.error(`[MONTHLY-REPORT] Error generating monthly report: ${error.message}`)
    }
}

// Schedule: Run at midnight on the 1st day of every month (0 0 1 * *)
cron.schedule("0 0 1 * *", () => {
    console.log("[MONTHLY-REPORT] Starting scheduled monthly revenue job...")
    sendMonthlyReport()
})

// Export for manual trigger if needed
module.exports = { sendMonthlyReport }
