const cron = require("node-cron")
const mongoose = require("mongoose")
const sib = require("@getbrevo/brevo")
const Order = require("../models/Order")
const User = require("../models/User")

const sendMonthlyReport = async () => {
    // Check if database is connected before running
    if (mongoose.connection.readyState !== 1) {
        return console.warn("[MONTHLY-REPORT] Skipping job: Database not connected")
    }

    try {
        const now = new Date()
        // Calculate first and last day of the previous month
        const firstDayPrevMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1)
        const lastDayPrevMonth = new Date(now.getFullYear(), now.getMonth(), 0, 23, 59, 59, 999)

        const monthName = firstDayPrevMonth.toLocaleString('default', { month: 'long' })
        const year = firstDayPrevMonth.getFullYear()

        console.log(`[MONTHLY-REPORT] Generating report for ${monthName} ${year}...`)

        // 1. Calculate Monthly Revenue using Aggregation
        const revenueData = await Order.aggregate([
            {
                $match: {
                    status: "completed",
                    createdAt: {
                        $gte: firstDayPrevMonth,
                        $lte: lastDayPrevMonth
                    }
                }
            },
            {
                $group: {
                    _id: null,
                    totalRevenue: { $sum: "$totalAmount" },
                    totalOrders: { $count: {} }
                }
            }
        ])

        const stats = revenueData.length > 0 ? revenueData[0] : { totalRevenue: 0, totalOrders: 0 }

        // 2. Fetch Admin Email Recipients
        const admins = await User.find({ role: "admin" })
        const recipientEmails = admins.reduce((acc, admin) => {
            if (admin.email) acc.push({ email: admin.email })
            if (Array.isArray(admin.emails)) {
                admin.emails.forEach(e => acc.push({ email: e }))
            }
            return acc
        }, [])

        // De-duplicate recipients
        const uniqueRecipients = Array.from(new Map(recipientEmails.map(item => [item.email, item])).values())

        if (uniqueRecipients.length === 0) {
            return console.warn("[MONTHLY-REPORT] No admin emails found. Report not sent.")
        }

        // 3. Configure Brevo Client
        const apiInstance = new sib.TransactionalEmailsApi()
        const apiKey = apiInstance.authentications['apiKey']
        apiKey.apiKey = process.env.BREVO_API_KEY

        const restaurantName = process.env.RESTAURANT_NAME || "OG Restaurant"
        const senderEmail = process.env.SENDER_EMAIL || "reports@ogrestaurant.com"
        const senderName = process.env.SENDER_NAME || restaurantName

        // 4. Send Email via Brevo
        const sendSmtpEmail = new sib.SendSmtpEmail()
        sendSmtpEmail.subject = `${restaurantName} Monthly Revenue Report - ${monthName} ${year}`
        sendSmtpEmail.htmlContent = `
<h2>${restaurantName} Monthly Revenue Report</h2>
<p><strong>Month:</strong> ${monthName} ${year}</p>
<hr />
<p><strong>Total Monthly Revenue:</strong> ₹${stats.totalRevenue.toLocaleString('en-IN')}</p>
<p><strong>Total Orders:</strong> ${stats.totalOrders}</p>
<hr />
<p>This is an automated report generated by your Restaurant Management System.</p>
    `
        sendSmtpEmail.sender = { "name": senderName, "email": senderEmail }
        sendSmtpEmail.to = uniqueRecipients

        const data = await apiInstance.sendTransacEmail(sendSmtpEmail)
        console.log(`[MONTHLY-REPORT] Brevo report sent successfully. Message IDs: ${data.messageIds?.join(', ')}`)

    } catch (error) {
        console.error(`[MONTHLY-REPORT] Error generating monthly report: ${error.message}`)
    }
}

// Schedule: Run at midnight on the 1st day of every month (0 0 1 * *)
cron.schedule("0 0 1 * *", () => {
    console.log("[MONTHLY-REPORT] Starting scheduled monthly revenue job...")
    sendMonthlyReport()
})

module.exports = { sendMonthlyReport }
