services:
  - type: web
    name: qr-restaurant-system-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_SOCKET_URL
        fromService:
          type: web
          name: qr-restaurant-system-backend
          property: url

  - type: web
    name: qr-restaurant-system-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: qr-restaurant-system-frontend
          property: url
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
